name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: rishank69/php-apache-docker@master
      with:
        url: "http://localhost:5656"
        user: "Rishabh Pandey"
        token: ${{ secrets.github_jenkins }}
        job: "job"
